spring:

  security:
    user:
      name: admin
      password: 1234

  datasource:
    url: jdbc:postgresql://localhost:5432/gira
    username: postgres
    password: admin
    
  flyway:
    enabled: false
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true